# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Johnatan
tagline:          'Desenvolvedor Web'
description:      'Desenvolvedor Web Apaixonado por aprender de tudo.'

author:
  name:           'Johnatan Tavares'
  url:            https://github.com/JohnatanT

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/JohnatanT/JohnatanT.github.io/
